### ISSUE TITLE
Toggle pencil/pen hotkey not working (MacOS Chrome)

### ISSUE THREAD

**Issue by jlindberg-oss** [nelhage/crossme#27]
Typing alt+p on MacOS inserts a literal π key, and does not toggle pencil/pen.

I suspect this would be fixed by adding `e.preventDefault()` here:
https://github.com/nelhage/crossme/blob/master/imports/components/puzzle.jsx#L217

**Comment by nelhage** [comment]
Thanks for the bug report! Any chance you can send that patch as a PR, and ideally test it locally? I don't have ready access to a Mac for testing, unfortunately.

If not, I can find to drop that fix in, since I agree it seems correct.

**Comment by jlindberg-oss** [comment]
Tested locally, and good call as my guess of the fix was wrong for 2 reasons.
